name: MLflow CI Retraining

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: mlflow
          auto-activate-base: false

      - name: Install MLflow & DagsHub
        shell: bash -l {0}
        run: |
          pip install mlflow dagshub

      - name: Run MLflow Project (Conda)
        shell: bash -l {0}
        env:
          DAGSHUB_USER_NAME: ${{ secrets.DAGSHUB_USER_NAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject

      - name: Build Docker image from MLflow model
        shell: bash -l {0}
        run: |
          mlflow models build-docker \
            -m runs:/latest/model \
            -n mkautsar/heart-disease-mlflow

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push mkautsar/heart-disease-mlflow
